### ISSUE TITLE
Disable Landfill research

### ISSUE THREAD

**Issue by mkaito** [MarcGamesons/factoriomod-cheaper-landfill#4]
This mod enables the landfill recipe without having to research it, and so the technology has no effect.

I propose to either disable the technology, or to set it to researched, instead of enabling the recipe.

**Comment by MarcGamesons** [comment]
Because my modding knowledge is quiet limited and I can't find the answer on how to change a recipe to already being researched, all I can do for now is to set the cost for the research to a very low amount so you don't waste resources on it.

If someone knows how to disable the need to research the technology I welcome that person to assist me in fixing this.
